### PR TITLE
removed incorrect test for Question 2.3

### PR DESCRIPTION
**Pull request by bendennes**
Question specifies:

"If the neighborhood sub-array does not fit in the grid even when considering wrapping around axis 1, then you should raise an error."

The test I have removed expected the function to return two rows when called on an element on the first row.

### CODE REVIEW

**Comment by lz381** [comment]
Thanks Ben, interesting perspective I hadn't considered...

I took that sentence in the question to mean if the radius extends far enough around the wrap to repeat elements (e.g. with s=2), an error should be thrown. I've not yet written a test for this as I don't think it's possible with assert statements - maybe with try/except (I'll give it a go later).

In this instance, I considered the neighbourhood sub-array of border elements to still 'fit in the grid'. The only difference is that the shape of the neighbourhood sub-array is limited by the hard border, but it's still a valid neighbourhood sub-array.

Otherwise, Conway's game of life (step(X)) would throw errors every time you called the extract() function for cells at the edge of the gird, which can still exhibit 'living' properties... maybe it's a good point for clarification from Mohamed?

**Comment by bendennes** [comment]
It's not entirely clear what he means, and I understand where you're coming from.

I agree that if the total width of the sub-array is greater than the width of the array itself (e.g. array shape (3,3), subarray with s=2)) then that should throw an error.

However, I understood "does not fit in the grid" as not allowing sub-arrays that don't fully fit in the array in axis 0 - i.e. would raise an error when called on an element in the first or last row.

You're right that this wouldn't work with the step(X) function, so I added a workaround at that point.

I'll ask Fabrizio on Teams and see what he says.

**Comment by lz381** [comment]
Cool thanks Ben! will keep my eyes peeled 👍

**Comment by lz381** [comment]
Looks like Fabrizio has clarified - it should throw an error, and no sub-arrays should be returned for a 'border' case. Will therefore merge this request. Thanks for the help Ben!

**Comment by bendennes** [comment]
No worries! I'm glad he was able to clarify - it was rather ambiguous

**Pull request merged**
